# integration tests for webcontainer ecosystem projects - scheduled or manual run for all suites
name: webcontainer-ecosystem-ci

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch:
    inputs:
      version:
        description: "@webcontainer/api version to use"
        required: true
        type: string
        default: "latest"
      suite:
        description: "testsuite to run"
        type: choice
        default: "all"
        options:
          - all
          - starters
          - tutorialkit
          - vitest-in-webcontainer
          - webcontainer-test

jobs:
  test-ecosystem:
    if: inputs.suite == 'all' || github.event_name == 'schedule'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - starters
          - tutorialkit
          - vitest-in-webcontainer
          - webcontainer-test
    steps:
      - uses: actions/checkout@v4

      - name: Run ${{ matrix.suite }}
        uses: ./.github/actions/ecosystem-run
        with:
          test-suite: ${{ matrix.suite }}
          version: ${{ inputs.version || github.event.client_payload.version || 'latest' }}

  test-ecosystem-selected:
    if: inputs.suite != 'all'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ${{ inputs.suite }}
        uses: ./.github/actions/ecosystem-run
        with:
          test-suite: ${{ inputs.suite }}
          version: ${{ inputs.version || github.event.client_payload.version }}
